### ISSUE TITLE
GD-16: .csproj names with space can throw an error when attemping to run tests

### ISSUE THREAD

**Issue by Kotzwinkle** [MikeSchulze/vscode-extension-gdunit3#16]
**The used GdUnit extension version:**

v2.2.5

**The used Visual Studio Code version:**

1.70.0

**The used Godot version:**

v3.5.stable.mono.official [991bb6ac7]

**OS including version:**

Windows 10

**Describe the bug**

The test runner will fail when given a .csproj whose name contains spaces and the following error is thrown:

`[EXCEPTION]: Command failed: dotnet build c:\src\my-project\My Project.csproj -verbosity:m`

I'm guessing that this could potentially be fixed by including quotes around the path (projectFile) when issuing the build command here in [src/testRunner.ts](https://github.com/MikeSchulze/vscode-extension-gdunit3/blob/a7e98f6c9431f0066c59a09ad7dce8fd608bc12f/src/testRunner.ts):

e.g.
``const fullCommand = `dotnet build "${projectFile}" -verbosity:m`; // ``

**Steps to Reproduce**

1. Create a new project within Godot Mono
2. Use a name with a space (ex. My Project)
3. Open the project in vscode and attempt to run test ing GdUnit Test Explorer

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue

Yes this should be easy fixed by uning quotes.
